"""add show_ranking field to donation_config

Revision ID: 108d02ceb0e6
Revises: 56b76a554bf0
Create Date: 2025-08-26 23:49:52.646825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108d02ceb0e6'
down_revision = '56b76a554bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空字段
    with op.batch_alter_table('donation_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_ranking', sa.Boolean(), nullable=True, comment='是否在首页显示捐赠排行榜入口'))
    
    # 更新所有现有记录的默认值
    op.execute("UPDATE donation_config SET show_ranking = 1 WHERE show_ranking IS NULL")
    
    # 将字段设置为NOT NULL
    with op.batch_alter_table('donation_config', schema=None) as batch_op:
        batch_op.alter_column('show_ranking', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_config', schema=None) as batch_op:
        batch_op.drop_column('show_ranking')

    op.create_table('donation_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_no', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('donor_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('donor_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('trade_no', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('payment_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('merchant_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('merchant_key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('notify_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('return_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
