"""Add project_name field to system_config table

Revision ID: 12218412b1c4
Revises: 16fff44585ef
Create Date: 2025-09-08 02:19:25.177182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12218412b1c4'
down_revision = '16fff44585ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=False, server_default='{{ project_name }}', comment='系统名称'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
