"""add last_import_time to dns_import_source

Revision ID: 56b76a554bf0
Revises: edd86eae04c3
Create Date: 2025-08-17 19:27:51.543898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b76a554bf0'
down_revision = 'edd86eae04c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_import_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_import_time', sa.DateTime(), nullable=True, comment='最后导入时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_import_source', schema=None) as batch_op:
        batch_op.drop_column('last_import_time')

    # ### end Alembic commands ###
