"""add dns test configuration fields

Revision ID: a209db130c87
Revises: cf3bbfc50249
Create Date: 2025-08-13 12:18:20.315468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a209db130c87'
down_revision = 'cf3bbfc50249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_dns_config')
    with op.batch_alter_table('dns_config', schema=None) as batch_op:
        batch_op.alter_column('apple_config_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('apple_doh_config_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('apple_dot_config_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dns_test_domain', sa.String(length=255), nullable=False, server_default='test.dns.con', comment='DNS检测域名'))
        batch_op.add_column(sa.Column('dns_test_port', sa.Integer(), nullable=False, server_default='5000', comment='DNS检测端口'))
        batch_op.add_column(sa.Column('dns_test_enabled', sa.Boolean(), nullable=False, server_default=sa.text('1'), comment='是否启用DNS检测功能'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('dns_test_enabled')
        batch_op.drop_column('dns_test_port')
        batch_op.drop_column('dns_test_domain')

    with op.batch_alter_table('dns_config', schema=None) as batch_op:
        batch_op.alter_column('apple_dot_config_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('apple_doh_config_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('apple_config_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    op.create_table('_alembic_tmp_dns_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doq_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('doq_server', sa.VARCHAR(length=255), nullable=True),
    sa.Column('doq_port', sa.INTEGER(), nullable=True),
    sa.Column('doq_description', sa.TEXT(), nullable=True),
    sa.Column('dot_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('dot_server', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dot_port', sa.INTEGER(), nullable=True),
    sa.Column('dot_description', sa.TEXT(), nullable=True),
    sa.Column('doh_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('doh_server', sa.VARCHAR(length=255), nullable=True),
    sa.Column('doh_port', sa.INTEGER(), nullable=True),
    sa.Column('doh_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('doh_description', sa.TEXT(), nullable=True),
    sa.Column('display_title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('apple_config_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('apple_doh_config_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('apple_dot_config_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
