"""Add DNS over HTTPS support

Revision ID: a2e3a3950d35
Revises: b6463ce1ad3b
Create Date: 2025-07-25 01:30:17.201741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e3a3950d35'
down_revision = 'b6463ce1ad3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doh_enabled', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('doh_server', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doh_port', sa.Integer(), nullable=True, server_default='443'))
        batch_op.add_column(sa.Column('doh_path', sa.String(length=255), nullable=True, server_default='/dns-query'))
        batch_op.add_column(sa.Column('doh_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_config', schema=None) as batch_op:
        batch_op.drop_column('doh_description')
        batch_op.drop_column('doh_path')
        batch_op.drop_column('doh_port')
        batch_op.drop_column('doh_server')
        batch_op.drop_column('doh_enabled')

    # ### end Alembic commands ###
