"""Add apple config controls

Revision ID: add_apple_config_controls
Revises: bae5d4b42063
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_apple_config_controls'
down_revision = 'bae5d4b42063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apple_config_enabled', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('apple_doh_config_enabled', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('apple_dot_config_enabled', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_config', schema=None) as batch_op:
        batch_op.drop_column('apple_dot_config_enabled')
        batch_op.drop_column('apple_doh_config_enabled')
        batch_op.drop_column('apple_config_enabled')
    # ### end Alembic commands ###