"""add openlist config table

Revision ID: add_openlist_config_table
Revises: edd86eae04c3
Create Date: 2025-01-07 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_openlist_config_table'
down_revision = 'edd86eae04c3'
branch_labels = None
depends_on = None


def upgrade():
    """创建OpenList配置表"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openlist_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用OpenList对接'),
    sa.Column('server_url', sa.String(255), nullable=True, comment='OpenList服务器地址'),
    sa.Column('username', sa.String(100), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(255), nullable=True, comment='密码'),
    sa.Column('sync_interval', sa.Integer(), nullable=False, comment='同步间隔(分钟)'),
    sa.Column('auto_sync', sa.Boolean(), nullable=False, comment='是否自动同步'),
    sa.Column('last_sync_time', sa.DateTime(), nullable=True, comment='最后同步时间'),
    sa.Column('sync_status', sa.String(50), nullable=True, comment='同步状态'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='访问令牌'),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True, comment='令牌过期时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    """删除OpenList配置表"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openlist_config')
    # ### end Alembic commands ###