"""add_sdk_table

Revision ID: add_sdk_table
Revises: add_vip_functionality
Create Date: 2025-01-13 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_sdk_table'
down_revision = 'add_vip_functionality'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create sdks table
    op.create_table('sdks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sdk_code', sa.String(length=32), nullable=False, comment='SDK充值码'),
        sa.Column('vip_days', sa.Integer(), nullable=False, comment='VIP天数'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='状态：unused-未使用，used-已使用，expired-已过期'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('used_at', sa.DateTime(), nullable=True, comment='使用时间'),
        sa.Column('used_by', sa.Integer(), nullable=True, comment='使用者用户ID'),
        sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者用户ID'),
        sa.Column('description', sa.String(length=200), nullable=True, comment='备注说明'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sdk_code')
    )
    
    # Create indexes for better performance
    op.create_index('idx_sdks_status', 'sdks', ['status'])
    op.create_index('idx_sdks_created_by', 'sdks', ['created_by'])
    op.create_index('idx_sdks_used_by', 'sdks', ['used_by'])
    op.create_index('idx_sdks_created_at', 'sdks', ['created_at'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_sdks_created_at', table_name='sdks')
    op.drop_index('idx_sdks_used_by', table_name='sdks')
    op.drop_index('idx_sdks_created_by', table_name='sdks')
    op.drop_index('idx_sdks_status', table_name='sdks')
    
    # Drop sdks table
    op.drop_table('sdks')
    
    # ### end Alembic commands ###