"""add_hide_amount_field_to_donation_config

Revision ID: b7b304b64075
Revises: 108d02ceb0e6
Create Date: 2025-08-26 23:53:33.812845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b304b64075'
down_revision = '108d02ceb0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support adding NOT NULL columns with default values directly
    # We need to do this in steps: add nullable column, update values, then make it NOT NULL
    
    # Step 1: Add the column as nullable
    with op.batch_alter_table('donation_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_amount', sa.Boolean(), nullable=True, comment='是否隐藏排行榜中的捐赠金额'))
    
    # Step 2: Update existing records with default value
    op.execute("UPDATE donation_config SET hide_amount = 0 WHERE hide_amount IS NULL")
    
    # Step 3: Make the column NOT NULL
    with op.batch_alter_table('donation_config', schema=None) as batch_op:
        batch_op.alter_column('hide_amount', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_config', schema=None) as batch_op:
        batch_op.drop_column('hide_amount')

    # ### end Alembic commands ###
