"""Initial migration with AI analysis tables

Revision ID: bae5d4b42063
Revises: 
Create Date: 2025-07-24 03:13:05.126245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae5d4b42063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adguard_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deepseek_api_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_analysis_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('analysis_threshold', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adguard_config', schema=None) as batch_op:
        batch_op.drop_column('analysis_threshold')
        batch_op.drop_column('auto_analysis_enabled')
        batch_op.drop_column('deepseek_api_key')

    # ### end Alembic commands ###
