"""Add payment tables

Revision ID: e96d74e4eae3
Revises: 56b76a554bf0
Create Date: 2025-08-26 01:08:13.543383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96d74e4eae3'
down_revision = '56b76a554bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_url', sa.String(length=255), nullable=False, comment='提交地址', server_default=''))
        batch_op.add_column(sa.Column('enable_alipay', sa.Boolean(), nullable=True, comment='启用支付宝'))
        batch_op.add_column(sa.Column('enable_wxpay', sa.Boolean(), nullable=True, comment='启用微信支付'))
        batch_op.add_column(sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='最小金额'))
        batch_op.add_column(sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='最大金额'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'))
        batch_op.alter_column('merchant_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('merchant_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('notify_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('return_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('return_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('notify_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('merchant_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('merchant_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('max_amount')
        batch_op.drop_column('min_amount')
        batch_op.drop_column('enable_wxpay')
        batch_op.drop_column('enable_alipay')
        batch_op.drop_column('submit_url')

    op.create_table('_alembic_tmp_payment_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('merchant_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('merchant_key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('api_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('notify_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('return_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('submit_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('enable_alipay', sa.BOOLEAN(), nullable=True),
    sa.Column('enable_wxpay', sa.BOOLEAN(), nullable=True),
    sa.Column('min_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('max_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
